Website/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Website.Models;
using Website.Areas.Admin.Filters;

namespace Website.Areas.Admin.Controllers
{
    [AdminAuthorizeFilter]
    public class DashboardController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Website/Areas/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website;

using Website.Models;
using Website.Areas.Admin.Filters;
using Website.Areas.Admin.Models;
using System.IO;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace Website.Areas.Admin.Controllers
{
    [AdminAuthorizeFilter]
    public class GalleryController : Controller
    {
        
        public ActionResult Index(int? day)
        {
            DBEntities db = new DBEntities();

            ViewData["day"] = day;

            return View();
        }

        [HttpPost]
        public JsonResult UpdateStatus(long id, bool value)
        {
            DBEntities db = new DBEntities();

            Photo entry = db.Photo.Find(id);
            if (entry != null)
            {
                entry.Status = value;
                db.Entry(entry).State = EntityState.Modified;
                db.SaveChanges();
            }

            return Json(new { value = entry.Status });
        }

        public JsonResult Data(jQueryDataTableParamModel param, int? day)
        {
           
            DBEntities db = new DBEntities();

            IQueryable<PhotoModel> all;

            if (day.HasValue) {
                DateTime  ToDay = new DateTime(2018, 11, 1, 0, 0, 0).AddDays(day.Value);
                DateTime EndDay = ToDay.AddDays(1).AddMilliseconds(-1);

                all = (from q in db.Photo
                        join a in db.Account on q.AccountID equals a.AccountID
                        select new PhotoModel
                        {
                            PhotoID = q.PhotoID,
                            Caption = q.Caption,
                            FileName = q.FileName,
                            CreateDate = q.CreateDate,
                            Status = q.Status,
                            Vote = db.Vote.Where(v =>
                                                    v.PhotoID == q.PhotoID &&
                                                    v.CreateDate >= ToDay &&
                                                    v.CreateDate <= EndDay
                                                ).Count(),
                            Account = new AccountModel
                            {
                                AccountID = a.AccountID,
                                Name = a.Name
                            }
                        });
            } 
            else
            {
                all = (from q in db.Photo
                       join a in db.Account on q.AccountID equals a.AccountID
                       select new PhotoModel
                       {
                           PhotoID = q.PhotoID,
                           Caption = q.Caption,
                           FileName = q.FileName,
                           CreateDate = q.CreateDate,
                           Status = q.Status,
                           Vote = db.Vote.Where(v => v.PhotoID == q.PhotoID).Count(),
                           Account = new AccountModel
                           {
                               AccountID = a.AccountID,
                               Name = a.Name
                           }
                       });
            }
            

            // filter

            IEnumerable<PhotoModel> filtered;
            if (!string.IsNullOrEmpty(param.sSearch))
            {
                filtered = all
                         .Where(a => a.Caption.Contains(param.sSearch) || a.Account.Name.Contains(param.sSearch));
            }
            else
            {
                filtered = all;
            }

            // sorting col

            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            Func<PhotoModel, dynamic> orderingFunction = (a => a.PhotoID.ToString());

            switch (sortColumnIndex)
            {
                case 0: orderingFunction = (a => a.PhotoID); break;
                case 1: orderingFunction = (a => a.FileName); break;
                case 2: orderingFunction = (a => a.Account.Name); break;
                case 3: orderingFunction = (a => a.Caption); break;
                case 4: orderingFunction = (a => a.Vote); break;
                case 5: orderingFunction = (a => a.Status); break;
                case 6: orderingFunction = (a => a.CreateDate); break;
            }

            // sorting dir

            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filtered = filtered.OrderBy(orderingFunction);
            else
                filtered = filtered.OrderByDescending(orderingFunction);

            // paging

            var displayed = filtered
                            .Skip(param.iDisplayStart)
                            .Take(param.iDisplayLength);

            // result

            var result = displayed.ToList().Select(a => new[]{
                a.PhotoID.ToString(),
                a.FileName,
                a.Account.Name,
                a.Caption,
                a.Vote.ToString(),
                a.Status.ToString(),
                a.CreateDate.ToString(),
                ""
            });

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = all.Count(),
                iTotalDisplayRecords = filtered.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Export(int? day)
        {
            DBEntities db = new DBEntities();

            IEnumerable<PhotoModel> qry;

            if (day.HasValue)
            {
                DateTime ToDay = new DateTime(2018, 11, 1, 0, 0, 0).AddDays(day.Value);
                DateTime EndDay = ToDay.AddDays(1).AddMilliseconds(-1);

                qry = (from q in db.Photo
                       join a in db.Account on q.AccountID equals a.AccountID
                       select new PhotoModel
                       {
                           PhotoID = q.PhotoID,
                           Caption = q.Caption,
                           FileName = q.FileName,
                           CreateDate = q.CreateDate,
                           Status = q.Status,
                           Vote = db.Vote.Where(v =>
                                                   v.PhotoID == q.PhotoID &&
                                                   v.CreateDate >= ToDay &&
                                                   v.CreateDate <= EndDay
                                               ).Count(),
                           Account = new AccountModel
                           {
                               AccountID = a.AccountID,
                               Name = a.Name
                           }
                       });
            }
            else
            {
                qry = (from q in db.Photo
                       join a in db.Account on q.AccountID equals a.AccountID
                       select new PhotoModel
                       {
                           PhotoID = q.PhotoID,
                           Caption = q.Caption,
                           FileName = q.FileName,
                           CreateDate = q.CreateDate,
                           Status = q.Status,
                           Vote = db.Vote.Where(v => v.PhotoID == q.PhotoID).Count(),
                           Account = new AccountModel
                           {
                               AccountID = a.AccountID,
                               Name = a.Name
                           }
                       });
            }

            var data = qry.ToList();
            var dataTable = new System.Data.DataTable("Photo");
            dataTable.Columns.Add("PhotoID", typeof(int));
            dataTable.Columns.Add("URL", typeof(string));
            dataTable.Columns.Add("Name", typeof(string));
            dataTable.Columns.Add("Caption", typeof(string));
            dataTable.Columns.Add("Vote", typeof(int));
            dataTable.Columns.Add("Status", typeof(string));
            dataTable.Columns.Add("CreateDate", typeof(DateTime));

            foreach (var item in data)
            {
                dataTable.Rows.Add(
                  item.PhotoID,
                  "https:" + WebConfig.BaseURL + "upload/gallery/" + item.FileName,
                  item.Account.Name,
                  item.Caption,
                  item.Vote,
                  item.Status.ToString(),
                  item.CreateDate
                );
            }

            var grid = new GridView();
            grid.ShowHeaderWhenEmpty = true;
            grid.DataSource = dataTable;
            grid.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=Photo.xls");
            Response.ContentType = "application/vnd.ms-excel";
            Response.Charset = "UTF-8";
            Response.BinaryWrite(System.Text.Encoding.UTF8.GetPreamble());

            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);

            grid.RenderControl(htw);

            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();

            return View("MyView");
        }
    }
}

Website/Areas/Admin/Views/Gallery/Index.cshtml
@{
    ViewBag.Title = "Register";

    int? day = (int?)ViewData["day"];

    int photos = 0;
    int votes = 0;
    
    DBEntities db = new DBEntities();
    
    if (day.HasValue) 
    {
        DateTime ToDay = new DateTime(2018, 11, 1, 0, 0, 0).AddDays(day.Value);
        DateTime EndDay = ToDay.AddDays(1).AddMilliseconds(-1);

        photos = db.Photo.Where(q => q.CreateDate >= ToDay && q.CreateDate <= EndDay).Count();
        votes = db.Vote.Where(q => q.CreateDate >= ToDay && q.CreateDate <= EndDay).Count();
    }
    else
    {
        photos = db.Photo.Count();
        votes = db.Vote.Count();
    }
}

<section class="panel">
	<header class="panel-heading">
		<h2 class="panel-title">List</h2>
	</header>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-8">
				<div class="mb-md">
                   <form class="form-horizontal" role="form">

                        <div class="form-group row">
                            <label for="inputKey" class="col-md-1 col-sm-2 col-xs-2 control-label">Day</label>
                            <div class="col-md-3 col-sm-3 col-xs-4">
                                <select id="select-day" class="form-control">
                                    <option value="">All</option>
                                    @for (int i = 1; i < 17; i++)
                                    { 
                                        <option value="@i" @(day.HasValue && day.Value == i ? "selected" : "")>@i</option>
                                    }
                                </select>
                            </div>
                            <div class="col-md-7 col-sm-6 col-xs-5">
                                <a id="export" class="btn btn-primary" href="@(Url.Action("Export") + "?day=" + day.ToString())">Export <i class="fa fa-report"></i></a>
                            </div>
                        </div>

                       <div class="form-group row">
                            <div class="col-md-12">
                                Total Photos: @photos
                            </div>
                           <div class="col-md-12">
                                Total Votes: @votes
                            </div>
                        </div>

                    </form>
				</div>
			</div>
		</div>
		<table class="table table-bordered table-striped" id="datatable">
			<thead>
				<tr>
					<th style="width:100px">ID</th>
					<th>Photo</th>
                    <th>User</th>
                    <th>Caption</th>
                    <th>Vote</th>
                    <th>Status</th>
                    <th>CreateDate</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</section>

@section Breadcrumb {
    <li><a href="@Url.Action("Index", "Dashboard")">Home</a></li>
	<li><span>Register</span></li>
}

@section scripts {
    <script>
        var $table = null;

        (function ($) {
            $(function () {
                $('#nev-contact').parent().addClass('nav-active');

                $table = $('#datatable').dataTable({
                    bProcessing: true,
                    bServerSide: true,
                    sAjaxSource: '@Url.Action("Data")',
                    fnServerParams: function (aoData) {
                        aoData.push({ name: "day", value: @(day.HasValue ? day.Value.ToString() : "null") });
                    },
                    aaSorting: [[0, 'desc']],
                    aoColumns: [
                        null,
                        { bSortable: false },
                        null,
                        null,
                        { sClass: "dt-right" },
                        null,
                        null
                    ],
                    fnCreatedRow: function (row, data, index) {
                        var id = data[0];

                        $(row).find('td').eq(1).html('<img src="@Url.Content("~/Upload/Gallery")/'+ data[1] +'" alt="" width="100" />');

                        var status = data[5];
                        var $switch = $('<div class="switch switch-sm switch-success"><input type="checkbox" id="chk-status-' + id + '"  value="true" data-plugin-ios-switch ' + (status == 'True' ? "checked=checked" : "") + ' /></div>');
                        $switch.find('input[type="checkbox"]').bind('change', { id: id }, function (e) {
                            var t = this;
                            updateStatus(t, e.data.id);
                        }).themePluginIOS7Switch();
                        $(row).find('td').eq(5).addClass('actions').css({ textAlign: 'center' }).html($switch);
                    
                        $(row).data('id', id);
                    },
                    fnDrawCallback: function (settings, json) {
                        
                    }
                 });
            });

            $('#select-day').change(function () {
                var d = $(this).val();

                window.location = '@Url.Action("Index")?day=' + d;
            });

        }).apply(this, [jQuery]);

        function updateStatus(t, id) {
            $.ajax({
                url: '@Url.Action("UpdateStatus")',
                type: 'POST',
                dataType: 'json',
                data: { "id": id, value: t.checked },
                traditional: true,
                success: function () {

                }
            });
        }
    </script>
}

@section styles {
    <style>
        .dt-right {
            text-align: right;
        }
    </style>
}
				