Website/Areas/Admin/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website;

using Website.Models;
using Website.Areas.Admin.Filters;

namespace Website.Areas.Admin.Controllers
{
   
    public class AdminUserController : Controller
    {
        [AdminAuthorizeFilter]
        public ActionResult Index()
        {
            return View();
        }

        [AdminAuthorizeFilter]
        public ActionResult Create()
        {
            return View("Edit", new AdminUser());
        }

        [AdminAuthorizeFilter]
        public ActionResult Edit(int? id)
        {
            return View(new DBEntities().AdminUser.Find(id));
        }

        [HttpPost, AdminAuthorizeFilter]
        public ActionResult Update(AdminUser entry)
        {
            try
            {
                DBEntities db = new DBEntities();
                AdminUser _entry = new AdminUser();

                if (entry.AdminUserID > 0) // Edit
                {
                    // if (!new AdminInPermissionService().IsCreateList(WebContext.AdminUserID.Value)) return RedirectToAction("index");

                    _entry = db.AdminUser.Find(entry.AdminUserID);
                    if (_entry == null) return RedirectToAction("index");
                }
                else // Create
                {
                    // if (!new AdminInPermissionService().IsEditList(WebContext.AdminUserID.Value)) return RedirectToAction("index");

                    string username = entry.UserName.Trim();

                    if (db.AdminUser.Where(q => q.UserName == username) == null)
                    {
                        ViewBag.Error = "User name invalid.";
                        return View("Create", entry);
                    }

                    _entry.UserName = username;
                    _entry.Name = entry.Name;
                    _entry.Password = Encryptor.MD5Hash(entry.Password);
                    _entry.CreateDate = DateTime.Now;
                    _entry.CreateBy = WebContext.AdminUserID.Value;
                }

                // field data
                _entry.Email = entry.Email;
                _entry.Level = entry.Level;
                _entry.UpdateDate = DateTime.Now;
                _entry.UpdateBy = WebContext.AdminUserID.Value;

                if (entry.AdminUserID  == 0)
                    db.AdminUser.Add(_entry);
                else
                    db.Entry(_entry).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Data invalid." + ex.Message;
                return View("Edit", entry);
            }
        }

        [AdminAuthorizeFilter]
        public ActionResult ChangePassword(long id)
        {
            return View(id);
        }

        [HttpPost, AdminAuthorizeFilter]
        public ActionResult ChangePassword(long id, string password)
        {
            try
            {
                if (WebContext.AdminUserLevel != 1) return RedirectToAction("index");

                DBEntities db = new DBEntities();
                AdminUser _entry = db.AdminUser.Find(id);

                if (_entry == null) return RedirectToAction("index");

                _entry.Password = Encryptor.MD5Hash(password);
                _entry.UpdateDate = DateTime.Now;
                _entry.UpdateBy = WebContext.AdminUserID.Value;

                db.Entry(_entry).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Data invalid." + ex.Message;
                return View("Edit", id);
            }
        }


        public ActionResult Login()
        {
            Login login = new Login();
            if (!string.IsNullOrEmpty(Request["next"])) login.Next = Request["next"];

            return View(login);
        }

        public ActionResult Logout()
        {
            WebContext.AdminUserID = null;
            return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult Login(Login login)
        {
            DBEntities db = new DBEntities();

            if (string.IsNullOrEmpty(login.UserName) || string.IsNullOrEmpty(login.Password))
            {
                login.Status = 1;
                login.Message = "*Username or password wrong";
                return View(login);
            }

            AdminUser user = db.AdminUser.Where(q => q.UserName == login.UserName).FirstOrDefault();
            if (user == null || user.Password != Encryptor.MD5Hash(login.Password))
            {
                login.Status = 2;
                login.Message = "*Username or password wrong";
                return View(login);
            }

            WebContext.AdminUserID = user.AdminUserID;
            WebContext.AdminUserLevel = user.Level;

            if (!string.IsNullOrEmpty(login.Next)) return Redirect(HttpUtility.UrlDecode(login.Next));

            return RedirectToAction("Index", "Dashboard");
        }

        [AdminAuthorizeFilter]
        public JsonResult Data()
        {
            var result = new DBEntities().AdminUser.ToList().Select(a => new[]{
                a.AdminUserID.ToString(),
                a.UserName,
                a.Level.ToString(),
                ""
            });

            return Json(new
            {
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, AdminAuthorizeFilter]
        public JsonResult Delete(long id)
        {
            DBEntities db = new DBEntities();
            //if (!new AdminInPermissionService().IsDeleteList(WebContext.AdminUserID.Value)) return Json(new { message = "false" });

            AdminUser entry = db.AdminUser.Find(id);
            if (entry != null)
            {
                db.Entry(entry).State = EntityState.Deleted;
                db.SaveChanges();
            }
                
            return Json(new { message = "true", result = "" });
        }

    }
}

Website/Controllers/GalleryController.cs
using Facebook;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;
using Website.Services;

namespace Website.Controllers
{
    [RequiresSSL]
    public class GalleryController : Controller
    {

        private DateTime ToDay
        {
            get 
            {
                return DateTime.Today;
            }
        }

        private DateTime EndDay
        {
            get
            {
                return ToDay.AddDays(1).AddMilliseconds(-1);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Images(string order, string keyword, int count, string token)
        {
            DBEntities db = new DBEntities();

            int accID = 0;

            if (!string.IsNullOrEmpty(token))
            { 
                Account acc = Services.AccountService.AccountBYToken(token);

                if (acc != null)
                    accID = acc.AccountID;
            }

            IQueryable<PhotoModel> qry = (from q in db.Photo
                                          join a in db.Account on q.AccountID equals a.AccountID
                                            where q.Status == true
                                            select new PhotoModel
                                            {
                                                PhotoID = q.PhotoID,
                                                Caption = q.Caption,
                                                FileName = q.FileName,
                                                CreateDate = q.CreateDate,
                                                Voted = accID > 0 && db.Vote.Where(v =>
                                                                        v.PhotoID == q.PhotoID &&
                                                                        v.AccountID == accID &&
                                                                        v.CreateDate >= ToDay &&
                                                                        v.CreateDate <= EndDay
                                                                    ).Count() > 0,
                                                Vote = db.Vote.Where(v => 
                                                                        v.PhotoID == q.PhotoID &&
                                                                        v.CreateDate >= ToDay && 
                                                                        v.CreateDate <= EndDay
                                                                    ).Count(),
                                                Account = new AccountModel { 
                                                    AccountID = a.AccountID,
                                                    Name = a.Name
                                                }
                                            });

            if (!string.IsNullOrEmpty(keyword))
            {
                qry = qry.Where(q => q.Caption.Contains(keyword) || q.Account.Name.Contains(keyword));
            }

            if (order == "vote")
            {
                qry = qry.OrderByDescending(q => q.PhotoID).OrderByDescending(q => q.Vote);
            }
            else
            {
                qry = qry.OrderByDescending(q => q.PhotoID);
            }


            qry = qry.Skip(count).Take(9);

            List<PhotoModel> photos = qry.ToList();

            return Json(photos);
        }

        public JsonResult Image(int id, string token)
        {
            DBEntities db = new DBEntities();

            int accID = 0;

            if (!string.IsNullOrEmpty(token))
            {
                Account acc = Services.AccountService.AccountBYToken(token);

                if (acc != null)
                    accID = acc.AccountID;
            }

            IQueryable<PhotoModel> qry = (from q in db.Photo
                                          join a in db.Account on q.AccountID equals a.AccountID
                                          where q.Status == true
                                          select new PhotoModel
                                          {
                                              PhotoID = q.PhotoID,
                                              Caption = q.Caption,
                                              FileName = q.FileName,
                                              CreateDate = q.CreateDate,
                                              Voted = accID > 0 && db.Vote.Where(v =>
                                                                      v.PhotoID == q.PhotoID &&
                                                                      v.AccountID == accID &&
                                                                      v.CreateDate >= ToDay &&
                                                                      v.CreateDate <= EndDay
                                                                  ).Count() > 0,
                                              Vote = db.Vote.Where(v =>
                                                                      v.PhotoID == q.PhotoID &&
                                                                      v.CreateDate >= ToDay &&
                                                                      v.CreateDate <= EndDay
                                                                  ).Count(),
                                              Account = new AccountModel
                                              {
                                                  AccountID = a.AccountID,
                                                  Name = a.Name
                                              }
                                          });

            return Json(qry.Where(q => q.PhotoID == id).FirstOrDefault());
        }


        public JsonResult UploadImage(string token, string image, string shareImage, string caption)
        {
            Account acc = AccountService.AccountBYToken(token);

            if (acc == null)
                return Json(new { error = "permission denied" });

            string imagePath = "~/Upload/Gallery/";
            string imageFileName = Guid.NewGuid() + ".png";

            System.IO.File.WriteAllBytes(Server.MapPath(imagePath + imageFileName), Convert.FromBase64String(image.Replace("data:image/png;base64,", "")));

            System.IO.File.WriteAllBytes(Server.MapPath(imagePath + "share_" + imageFileName), Convert.FromBase64String(shareImage.Replace("data:image/png;base64,", "")));

            Photo photo = new Photo {
                AccountID = acc.AccountID,
                FileName = imageFileName,
                Caption = caption,
                Vote = 0,
                Share = 0,
                Status = true,
                CreateDate = DateTime.Now
            };

            DBEntities db = new DBEntities();

            db.Photo.Add(photo);
            db.SaveChanges();

            var facebookClient = new FacebookClient(token);

            var postParams = new
            {
                scrape = true,
                id = "https:" + WebConfig.BaseURL + "gallery/photo/" + photo.PhotoID
            };
           
            facebookClient.Post(postParams);

            photo.FileName = "https:" + WebConfig.BaseURL + "gallery/photo/" + photo.PhotoID;

            return Json(photo);
        }

        public JsonResult Vote(string token, int id) 
        {
            Account acc = AccountService.AccountBYToken(token);

            if (acc == null)
                return Json(new { error = "permission denied" });

            DBEntities db = new DBEntities();

            Photo photo = db.Photo.Find(id);

            if (photo == null)
                return Json(new { error = "data invalid" });

            int voteCount = db.Vote.Where(q => 
                q.PhotoID == photo.PhotoID && 
                q.AccountID == acc.AccountID &&
                q.CreateDate >= ToDay && 
                q.CreateDate <= EndDay
            ).Count();

            if (voteCount == 0)
            {
                Vote vote = new Vote
                {
                    PhotoID = photo.PhotoID,
                    AccountID = acc.AccountID,
                    CreateDate = DateTime.Now
                };

                db.Vote.Add(vote);
                db.SaveChanges();

                // daily
                photo.Vote = db.Vote.Where(q => 
                    q.PhotoID == photo.PhotoID &&
                    q.CreateDate >= ToDay && 
                    q.CreateDate <= EndDay
                ).Count();

                db.Entry(photo).State = System.Data.EntityState.Modified;

                db.SaveChanges();

                return Json(new { count = photo.Vote });
            }
            else
            {
                return Json(new { error = "voted" });
            }
            
        }

        public ActionResult Photo(int id)
        {
            DBEntities db = new DBEntities();

            Photo photo = db.Photo.Find(id);

            if (photo == null)
                return RedirectToAction("Index", "Home");

            Account account = db.Account.Find(photo.AccountID);

            if (account == null)
                return RedirectToAction("Index", "Home");

            Photo p = new PhotoModel
            {
                PhotoID = photo.PhotoID,
                FileName = photo.FileName,
                Account = new AccountModel
                {
                    Name = account.Name
                }
            };

            return View(p);

        }
    
    }
}

Website/Areas/Admin/Views/Shared/Layout.cshtml
@using Website.Areas.Admin

@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutBase.cshtml";
    
    
    string adminName = "";
    string adminEmail = "";
    string adminRole = "";

    AdminUser admin = new DBEntities().AdminUser.Find(WebContext.AdminUserID.Value);
    if (admin != null) {
        adminName = admin.Name;
        adminEmail = admin.Email;
        
        switch (admin.Level) {
            case 1: adminRole = "System Amin"; break;
            case 2: adminRole = "Amin"; break;
            case 3: adminRole = "User"; break;
        }
    }

}

<!-- start: header -->
<header class="header">
	<div class="logo-container">
		<a href="/" class="logo">
			@*<img src="@Url.Content("~/backend_assets/images/logo.png")" height="35" alt="Porto Admin" />*@
            @WebConfig.SiteTitle
		</a>
		<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
			<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
		</div>
	</div>
			
	<!-- start: search & user box -->
	<div class="header-right">
		<div id="userbox" class="userbox">
			<a href="#" data-toggle="dropdown">
				<figure class="profile-picture">
					<img src="@Url.Content("~/backend_assets/images/!logged-user.jpg")" alt="Joseph Doe" class="img-circle" data-lock-picture="assets/images/!logged-user.jpg" />
				</figure>
				<div class="profile-info" data-lock-name="@adminName" data-lock-email="@adminEmail">
					<span class="name">@adminName</span>
					<span class="role">@adminRole</span>
				</div>
			
				<i class="fa custom-caret"></i>
			</a>
			
			<div class="dropdown-menu">
				<ul class="list-unstyled">
					<li class="divider"></li>
					<li>
						<a role="menuitem" tabindex="-1" href="#"><i class="fa fa-user"></i> My Profile</a>
					</li>
					<li>
						<a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
					</li>
					<li>
						<a role="menuitem" tabindex="-1" href="@Url.Action("logout", "AdminUser")"><i class="fa fa-power-off"></i> Logout</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- end: search & user box -->
</header>
<!-- end: header -->

<div class="inner-wrapper">
	<!-- start: sidebar -->
	<aside id="sidebar-left" class="sidebar-left">
				
		<div class="sidebar-header">
			<div class="sidebar-title">
				Navigation
			</div>
			<div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
				<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
			</div>
		</div>
				
		<div class="nano">
			<div class="nano-content">
				<nav id="menu" class="nav-main" role="navigation">
					<ul class="nav nav-main">
                        
                        @if(WebContext.AdminUserLevel == (int)AdminLevelEnum.SystemAdmin){
                        <li>
							<a href="@Url.Action("Index", "AdminUser")" id="nev-admins">
								<i class="fa fa-users" aria-hidden="true"></i>
								<span>Admin Users</span>
							</a>
						</li>
                        }

                        <li>
							<a href="@Url.Action("Index", "Gallery")" id="nev-interested">
								<i class="fa fa-copy" aria-hidden="true"></i>
								<span>Gallery</span>
							</a>
						</li>
                        
                        <li>
							<a href="@Url.Action("Logout", "AdminUser")">
								<i class="fa fa-power-off" aria-hidden="true"></i>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
				
		</div>
				
	</aside>
	<!-- end: sidebar -->

	<section role="main" class="content-body">
		<header class="page-header">
			<h2>@ViewBag.Title</h2>
					
			<div class="right-wrapper pull-right">
				<ol class="breadcrumbs">
					<li>
						<a href="@Url.Action("Index", "Dashboard")">
							<i class="fa fa-home"></i>
						</a>
					</li>
                    @RenderSection("Breadcrumb", true)
				</ol>
					
				<a class="sidebar-right-toggle" data-open="">@*<i class="fa fa-chevron-left"></i>*@</a>
			</div>
		</header>

		<!-- start: page -->
        @RenderBody()
		<!-- end: page -->
	</section>
</div>

@section Styles {
    @RenderSection("Styles", false) 
}

@section scripts {
    @RenderSection("Scripts", false) 
}

Website/Areas/Admin/Views/Shared/LayoutBase.cshtml
<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap/css/bootstrap.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/font-awesome/css/font-awesome.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/magnific-popup/magnific-popup.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-datepicker/css/datepicker3.css")" />

        <!-- Specific Page Vendor CSS -->
        <link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/select2/select2.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/dropzone/css/basic.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/dropzone/css/dropzone.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-markdown/css/bootstrap-markdown.min.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/summernote/summernote.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/summernote/summernote-bs3.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/codemirror/lib/codemirror.css")" />
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/codemirror/theme/monokai.css")" />
        <link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/bootstrap-fileupload/bootstrap-fileupload.min.css")" />
        <link rel="stylesheet" href="@Url.Content("~/backend_assets/vendor/jquery-datatables-bs3/assets/css/datatables.css")" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/stylesheets/theme.css")" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/stylesheets/skins/default.css")" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="@Url.Content("~/backend_assets/stylesheets/theme-custom.css")">

		<!-- Head Libs -->
		<script src="@Url.Content("~/backend_assets/vendor/modernizr/modernizr.js")"></script>

        @RenderSection("Styles", false)
	</head>
	<body>
        <section class="body">
		    <!-- start: page -->
		    @RenderBody()
		    <!-- end: page -->

		    <!-- Vendor -->
		    <script src="@Url.Content("~/backend_assets/vendor/jquery/jquery.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap/js/bootstrap.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/nanoscroller/nanoscroller.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/magnific-popup/magnific-popup.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-placeholder/jquery.placeholder.js")"></script>
            <script src="@Url.Content("~/backend_assets/vendor/jquery-tablednd/jquery.tablednd.js")"></script>

            <!-- Specific Page Vendor -->
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js")"></script>
            <script src="@Url.Content("~/backend_assets/vendor/jquery-validation/jquery.validate.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-datatables/media/js/jquery.dataTables.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-datatables-bs3/assets/js/datatables.js")"></script>

		    <script src="@Url.Content("~/backend_assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/select2/select2.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/jquery-maskedinput/jquery.maskedinput.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/fuelux/js/spinner.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/dropzone/dropzone.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-markdown/js/markdown.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-markdown/js/to-markdown.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-markdown/js/bootstrap-markdown.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/lib/codemirror.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/addon/selection/active-line.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/addon/edit/matchbrackets.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/mode/javascript/javascript.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/mode/xml/xml.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/mode/htmlmixed/htmlmixed.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/codemirror/mode/css/css.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/summernote/summernote.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/bootstrap-maxlength/bootstrap-maxlength.js")"></script>
		    <script src="@Url.Content("~/backend_assets/vendor/ios7-switch/ios7-switch.js")"></script>
            <script src="@Url.Content("~/backend_assets/vendor/bootstrap-fileupload/bootstrap-fileupload.min.js")"></script>
		    
		    <!-- Theme Base, Components and Settings -->
		    <script src="@Url.Content("~/backend_assets/javascripts/theme.js")"></script>
		
		    <!-- Theme Custom -->
		    <script src="@Url.Content("~/backend_assets/javascripts/theme.custom.js")"></script>
		
		    <!-- Theme Initialization Files -->
		    <script src="@Url.Content("~/backend_assets/javascripts/theme.init.js")"></script>


            <!-- ckeditor -->
            <script src="@Url.Content("~/backend_assets/vendor/ckeditor/ckeditor.js")"></script>
            <script src="@Url.Content("~/backend_assets/vendor/ckeditor/adapters/jquery.js")"></script>
            <script src="@Url.Content("~/backend_assets/vendor/ckfinder/ckfinder.js")"></script>
            <script type="text/javascript">
                $(function () {
                    var $editor = $('#description-th,#description-en,.wysiwyg').ckeditor();
                    if ($editor.length > 0) {
                        var editor = $editor.ckeditorGet();
                        CKFinder.setupCKEditor(editor, '@Url.Content("~/backend_assets/vendor/ckfinder/")');
                    }
                });
            </script>
           
            <!-- Theme Initialization Files -->
            @RenderSection("Scripts", false)
        </section>
	</body>
</html>